---
apiVersion: v1
kind: Service
metadata:
  name: green
  labels:
    app: green
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: green
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  labels:
    app: green
spec:
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      name: green
      labels:
        app: green
    spec:
      containers:
        - name: bluegreen
          image: "eu.gcr.io/gardener-project/test/martinweindel/bluegreen:0.1"
          imagePullPolicy: IfNotPresent
          env:
          - name: COLOR
            value: green
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
